# Generated by Django 5.2.7 on 2025-12-02 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='password',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
