# Generated by Django 5.2.7 on 2025-12-02 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0003_remove_teammember_password_teammember_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='password',
            field=models.CharField(blank=True, help_text='Set the login password for this team member', max_length=128),
        ),
    ]
